name: Build, QA, Release

on: push

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FONTFORGE_COMMIT: aa062f4cbd1db21e27b2620f16993ebe4c540ab6

jobs:
  build-ttf:
    runs-on: ubuntu-latest
    name: Build main TTFs
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Ubuntu requirements
      run: |
        sudo apt-get update
        sudo apt-get -qy --no-install-recommends install \
          build-essential \
          cmake \
          ninja-build \
          packaging-dev \
          pkg-config
    - name: Install fontforge
      run: |
        curl -Lo fontforge.zip https://github.com/fontforge/fontforge/archive/${{ env.FONTFORGE_COMMIT }}.zip
        unzip fontforge.zip
        mv fontforge-${{ env.FONTFORGE_COMMIT }} fontforge
        cd fontforge
        curl -O https://patch-diff.githubusercontent.com/raw/fontforge/fontforge/pull/4232.patch
        patch -p1 <4232.patch
        mkdir build
        cd build
        cmake -G Ninja \
          -D CMAKE_INSTALL_PREFIX="$PWD/target" \
          -D ENABLE_DOCS=OFF \
          -D ENABLE_GUI=OFF \
          -D ENABLE_LIBGIF=OFF \
          -D ENABLE_LIBJPEG=OFF \
          -D ENABLE_LIBPNG=OFF \
          -D ENABLE_LIBREADLINE=OFF \
          -D ENABLE_LIBSPIRO=OFF \
          -D ENABLE_LIBTIFF=OFF \
          -D ENABLE_LIBUNINAMESLIST=OFF \
          -D ENABLE_PYTHON_EXTENSION=ON \
          -D ENABLE_NATIVE_SCRIPTING=OFF \
          -D ENABLE_WOFF2=OFF \
          .. \
        ;
        ninja
        sudo ninja install
    - name: Add site-packages to default search path
      run: echo "PYTHONPATH=$PWD/fontforge/build/target/lib/python${{ env.PYTHON_VERSION }}/site-packages:$PYTHONPATH" >>"$GITHUB_ENV"
    - name: Build fonts
      run: make build
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: fontbuild-ttf
        path: fonts
